### ISSUE TITLE
ES6 and JSX support

### ISSUE THREAD

**Issue by osenvosem** [jonschlinkert/sublime-markdown-extended#104]
Please add ES6 and JSX support.
Now it looks like:
![screen shot 2015-10-12 at 10 10 04](https://cloud.githubusercontent.com/assets/6762673/10422923/ac49366c-70c9-11e5-9500-69e28be8c5bb.png)
And this is Babel highlighting:
![screen shot 2015-10-12 at 10 10 12](https://cloud.githubusercontent.com/assets/6762673/10422931/baeb0e84-70c9-11e5-83e0-f5aa5ef6f7d3.png)

**Comment by jonschlinkert** [comment]
sure, I can add this next time I have a chance to make edits. or would you like to do a pr?

**Comment by iHedgehog** [comment]
@jonschlinkert I would like to with pleasure, if I had enough skills for that.
Btw, I asked you to add twig support on the 12th of May. Today is the 12th of October. Such a coincidence.

**Comment by tomchentw** [comment]
@jonschlinkert I'd love to help out this since currently the color just breaks for JSX elements, making it very ugly and weird.

For what I can tell, I should modify some places from these code block sections:
https://github.com/jonschlinkert/sublime-markdown-extended/blob/master/Syntaxes/Markdown%20Extended.sublime-syntax#L265-L279

and to change syntax highlighter to use babel. Am I correct?

**Comment by nathanmarks** [comment]
@tomchentw did you fork this with any luck?

**Comment by jonschlinkert** [comment]
I should have closed this before. the "strange coloring" is from [changes in ST3](https://github.com/jonschlinkert/sublime-monokai-extended/issues/62), some of which seem unfixable at this level. 

@tomchentw @nathanmarks fork the hell out of it. this is open source, I do this in my spare time. I'm glad people get value of the package, but every time someone makes a comment like that it makes me want to make all of my repos private.
