### ISSUE TITLE
Markdown extended break shell syntax with st3 > 3118

### ISSUE THREAD

**Issue by BarbUk** [jonschlinkert/sublime-markdown-extended#138]
As reported in https://github.com/sublimehq/Packages/issues/565, with sublime text > 3118, Shell-Unix-Generic.sublime-syntax do not work anymore with the following error:

Error loading syntax file "Packages/ShellScript/Shell-Unix-Generic.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

![image](https://cloud.githubusercontent.com/assets/64371/17613338/17716a3e-606d-11e6-9dac-551d91d581f8.png)

Removing the package or disabling it resolve the problem.

Tested on st3 3119 and 3120 on OSX 10.10.

**Comment by jonschlinkert** [comment]
How is that associated with this library? Sounds like a false positive to me

**Comment by FichteFoll** [comment]
`Markdown Extended.sublime-syntax` doesn't appear to be using `with_prototype` patterns for including shell, so it's probably caused by something else.

**Comment by BarbUk** [comment]
Indeed.
Just did a fresh install and don't have the problem anymore.

**Comment by doublerebel** [comment]
I had this same issue, and I believe I found the cause:

In User `Preferences.sublime-settings`, I had `"Markdown"` in the `"ignored_packages"` list.  Removing it from the list and restarting fixes the issue for me.

A similar bug caused by the setting is at [SublimeText-Markdown/MarkdownEditing#115](https://github.com/SublimeText-Markdown/MarkdownEditing/issues/115).

**Comment by jonschlinkert** [comment]
thanks for the updates guys!

**Comment by cryptostrophe** [comment]
I was also having this issue on Build 3120, but my only `ignored_packages` were `Vintage` and `Vintageous`. Turns out I had installed [CSS3](https://github.com/y0ssar1an/CSS3) without disabling the built-in CSS package—once I did that and restarted Sublime, the Markdown Extended "sanity limit" error message went away.
