### ISSUE TITLE
combine latex and markdown highlighting

### ISSUE THREAD

**Issue by puterleat** [jonschlinkert/sublime-markdown-extended#19]
Using inline latex is a pretty common pattern in markdown documents destined for conversion with pandoc. 

For example, one might include the command \textsc{small caps text} in a pandoc markdown doc because markdown has no native syntax for small caps.

However at present I can't work out how to get both markdown and latex syntax highlighting active at the same time. It would also be nice if the document tree (for ctrl-R) recognised both markdown headings and \part{} \chapter{} and \section{} commands.

**Comment by jonschlinkert** [comment]
closing due to age

**Comment by hadim** [comment]
That would be a really usefull feature since one of software which make write markdown is pandoc. And pandoc allows raw LaTex commands.

Could you at least add syntax and color features for two things:

- math equations which can take two forms : `$ inline equation $` or `$$ multiline equation $$`
- bibliography key reference such as `[@my_bib_key]`

Thank you !

**Comment by jonschlinkert** [comment]
@hadim can you open a new issue to discuss? thanks
