### ISSUE TITLE
Breaks with a bold strings containing under-scores

### ISSUE THREAD

**Issue by pradyunsg** [jonschlinkert/sublime-markdown-extended#96]
Markdown Extended highlights the text below incorrectly as seen in the image.

```
Some Text **GITHUB_USERNAME** and **GITHUB_PASSWORD** Some Text
```

![screenshot](https://cloud.githubusercontent.com/assets/3275593/8499994/e11eb596-21b5-11e5-896e-de44a5ca138b.png)

The issue seems to be when there are 2 bold text-segments with underscore in both of them. (This mis-highlighting is not seen when either of the under-scores are removed.)

**Comment by jonschlinkert** [comment]
Closing since I'm not able to reproduce and this can be caused by other packages. Here is how it looks for me:

<img width="377" alt="screen shot 2015-10-12 at 5 34 55 am" src="https://cloud.githubusercontent.com/assets/383994/10425119/0579c8d6-70a3-11e5-8efb-0f8575dc6e41.png">

if you or anyone else has a way for me to reproduce let me know so we can reopen and get it fixed

**Comment by pradyunsg** [comment]
Try it with the same text. :expressionless: 

It's because of two underscores in the same line.

**Comment by jonschlinkert** [comment]
well that wasn't even a nuance was it lol. reopening

**Comment by jonschlinkert** [comment]
I think this is related https://github.com/jonschlinkert/sublime-markdown-extended/issues/61

**Comment by pradyunsg** [comment]
Ani updates?

**Comment by pradyunsg** [comment]
Closing in favour of #61.
